<?php

return [
"make a blaze farm",
"Brew a potion",
"make an alchemy lab",
"create a nether portal room/temple around your nether portal",
"create an automatic melon and pumpkin farm",
"Relieve a Blaze of its rod",
"create a cactus farm",
"build an enchanting room",
"build a huge castle or mansion",
"find the stronghold",
"defeat the dragon",
"drain an ocean monument",
"make a guardian farm",
"build a lighthouse",
"make crazy pixel art",
"Make a full set of Iron Tools.",
"Collect a complete stack of Redstone Dust.",
"Make upgrades to your current defensive structures. (Arrow Turrets, Golems, Traps.)",
"Spawn the Wither",
"Make upgrades to your farm. (Expand, Add more varienty of food, Add an infinite water supply.)",
"Starting working on a Mining Shaft.",
"Build an automated Minecart Delivery System.",
"Locate a Pre-Made Mineshaft, a Ravine, Or a Village.",
"Build an animal farm.",
"Make additional rooms in your house for specific tasks. (Kitchen, Enchanting Room, Storage Room.)",
"Make plenty of Bookshelves.",
"Collect a complete stack of Iron, 9 Diamonds, and two complete stacks of coal.",
"Make some Diamond Tools.",
"Build additional shacks near your house for future villagers.",
"Build something using redstone. (Automate your farm, Piston doors, Better Traps.)",
"Upgrade your house and its defensive structures. (Archer Towers, Thicker Walls, Decorations.)",
"Collect 32 Obsidian.",
"Build an Enchanting Table, Enchant a Tool, Test out Enchanted Tool.",
"Build a Nether Portal.",
"Make two sets of Iron Armor, a Diamond Sword, Enchant a Bow, and Make a stack of Arrows.",
"Enter the Nether.",
"Build a shack around your Nether Portal in both dimensions.",
"Collect two stacks of Glowstone Dust and Nether Quartz.",
"Locate a Nether Fortress.",
"Destroy a Blaze Spawner, Kill 5 Wither Skeletons, 8 Ghasts, and Collect 10 Netherwart.",
"Use the items from your Nether Adventure to decorate your land.",
"https://www.jeuxvideo.com/news/1471441/minecraft-voici-nos-meilleurs-tutos-pour-des-idees-de-construction.htm",
"Make a Brewing Stand, A Cauldron, Infinite Water Supply, and A steady supply of Netherwart.",
"Make 5 different potions, each with their own type of effect.",
"Trap 4 Zombie Villagers in your land.",
"Turn them into Villagers and provide safe havens for them.",
"Make more villager houses and upgrade your current shacks.",
"Breed until you have one of each Villager type.",
"Make an Iron Golem Farm.",
"Build a wall around your entire land, supply proper lighting, decorate the villagers houses, and add a fountain to it.",
"Enchant 5 books and then enchant a Wooden Sword with 3 different enchantments and give it a silly name.",
"Decide on a name for your town and build a wool flag for the top of your house.",
"Build a Library, Blacksmith, Shop/Bazaar, Park, and an Animal Shelter.",
"Collect a full stack of Emeralds.",
"Trade with a villager until they have a new item for sale.",
"Build a map and explore atleast 500 blocks away from your house.",
"Fight the Wither.",
"Defeat the Enderdragon on your first try.",
"Save a villager from a Zombie attack.",
"Build a Beacon.",
"Ride a Pig.",
"Build something and have it hidden.",
"Visit 5 different biome types.",
"Build your house where 3 different biomes meet.",
"Break 4 bridges in a Nether Fortress.",
"Use TNT on 3 different Animals, 3 Different Hostile Mobs, and 3 Villagers.",
"Breed some sheep and dye them until you have 10 different colored sheep.",
"Find a dungeon and spit on the spawner. (Dump a bucket of water on it.)",
"Kill a Wither Skeleton with an enchanted Fishing Rod. (Film it too, I'd like to see that.)",
"Craft and place a Flower Pot.",
"Gather all 16 colors of wool",
"Swim in lava while having the Fire Resistance effect.",
"Befriend five Wolves.",
"Make a Water Slide! (YAAAAY!! Fun!)",
"Beat an Iron Golem in a match of fisti-cuffs. (Bare-handed brawlers are badass and it's guaranteed to get you laid.)",
"Eat an Enchanted Apple",
"Tame an Ocelot and make it fight a wild Wolf.",
"Enchant a brick with a useless enchantment and punch Squid with it. (Apparently only available in creative.)",
"Dump a Bucket of Water next to an Enderman.",
"Use Potions of Speed on Pigs and ride one. (I do not condone driving under the influence, unless it's on a pig or turtle.)",
"Throw Potions of Invisibility at Bats and make ghosts!",
"Lead a Cow to water, and make it drink/cross it!",
"Make a pumpkin farm",
"Make a melon farm",
"Make a potato farm",
"Gain the trust of an Ocelot",
"Make a carrot farm",
"Make a nether wart farm",
"Kill a blaze",
"Create an Iron Golem",
"Make an animal farm",
"Breed some animals",
"Get a disc from a creeper",
"Make some fireworks",
"Cure a zombie villager",
"Find a village",
"Explore 5 ravines",
"Kill a spider jockey",
"Find the stronghold",
"Kill the ender dragon",
"Make a nether portal",
"Kill a ghast",
"Get a pet dog",
"Get a pet cat",
"Explore EVERY biome",
"Create something simple with redstone",
"Use a cauldron to dye all 4 unique pieces of leather armor.",
"Create something advanced with redstone",
"Find lapis lazuli",
"Find diamond",
"Get every color of wool",
"Craft a set of iron armor",
"Craft a set of diamond armor",
"Craft a set of iron tools",
"Craft a set of diamond tools",
"Enchant a book",
"Write in a book",
"Make an enchantment table",
"Make an anvil",
"Rename something",
"Explore an abandoned mineshaft",
"Enchant a tool",
"Enchant armor",
"Reach level 30",
"Reach level 50",
"Reach level 100",
"Create a sugar cane farm",
"Craft 64 slabs of every wood color",
"Create a cactus farm",
"Get thorns I, II, or III enchantment",
"Craft an ender chest",
"Craft a beacon",
"Craft an emerald block",
"Kill a mob while wearing the same type of mob head.",
"Craft a diamond block",
"Craft a lapis lazuli block",
"Craft a gold block",
"Craft an iron block",
"Make a potion",
"Craft an Ender Chest",
"Craft a beacon",
"Craft an emerald block",
"Trade with a villager",
"Build a large glass snowglobe. Put a comically small house inside and lure in a few villagers to inhabit it.",
"Make a banner using an Enchanted Apple Stencil",
"Track down that blaze farm you swore you would pretty up some day but you never got around to it. Build a pixel art blaze head around it. This goes for any mob farm.",
"Connect two based with a large suspended bridge. It can tunnel through mountains or wrap around them. Lay some track and use minecarts to travel from base to base in style.",
"Place a bunch of hoops in the air suspended by balloons. When you're bored, fly through them with an elytra.",
"Create a study complete with book shelves, a desk, a hammock and a map wall.",
"Place 9 fully explored, adjacent map items into 9 item frames in a 3 by 3 square.",
"Find an area that you'll never look at from the ground, but you could see from an aerial view. Build some horizontal pixel art there. When you fly over with your elytra or map the area, you'll see it.",
"Build a bonfire area. Add some benches and chairs. Add some burning netherrack and your best attempt at coals or ash so it looks like a fire was just roaring, but is now just some loose coals and a few pieces of still burning wood.",
"Befriend twenty stray cats.",
"Breed two pandas with bamboo",
"Travel a ways away from your main base and build a resort in your favorite warm biome. Make it somewhere you'd try to visit in real life. Add pools, gambling areas, restaurants, tanning beds, a large flat screen TV, whatever would make you want to vacation there.",
"Defeat a Ravager.",
"Trade for the best possible price",
"Add a few camp grounds to a wooded area. Add an RV or two, some hiking paths, a ticket area, and maybe some villagers to look after the place.",
"Choose a happy moment from your childhood and rebuilt it somewhere in your world. Birthdays, getting a new pet, when you achieved something you were proud of, whatever moment makes you smile. Re-create that scene in your world in as much detail as you can.",
"Make your own personal Mount Rushmore by carving the faces of a few people you respect into a mountain.",
"Use a Grindstone to get experience from an enchanted item",
"Walk in a village with the Bad Omen effect applied",
"Use a Hopper to move an item from a Chest Minecart to a Chest.",
"Finish an unfinished project. If you're like me, you have about twenty just begging to be completed.",
"Receive a gift from a tamed cat in the morning.",
"Decorate the entrance to your mine with piles of ores, a forge, a few anvils and a place for hungry and tired miners to sit down and grab a bite to eat.",
"Build a ranch next to your farming area. Add a windmill or watermill to grind wheat into flour, a villager named "Farmer Joe," and some fenced in animals.",
"Recreate a scene in whatever video game gives you nostalgia. For me it would be Lumbridge Castle.",
"Ring the bell with a hostile enemy in the village",
"Build a large train next to your rail system. Make it look like it's out of service and set to the side so it doesn't block your rail way. Build a caboose, a few passenger cars with luggage and villagers, a meal car, and an engine.",
"Give someone a suspicious stew",
"Build a massive dragon or some other monster terrorizing your town. Add some destruction, some screaming citizens, and a hero coming to save the day. Make it look like the event is frozen in time.",
"Cut down a small area of forest, leaving only tree stumps. Place a zombie holding an axe inside a prison cell. Build a police car and make it look like he's being arrested for taking down the forest.",
"Place scaffolding to the world limit",
"Use a Campfire to collect Honey from a Beehive using a Bottle without aggravating the bees.",
"Give a naturally generated structure an upgrade. Make a witch hut into a mansion, give a woodland mansion some interior decoration, or improve the defenses of a jungle temple.",
"Build a bunch of tree houses in a jungle and connect them with rope bridges.",
"Take over a ravine. Build a few bridges winding down ravine walls, and carve rooms into the walls.",
"Move and place a Bee Nest, with 3 bees inside, using Silk Touch.",
"Connect 3 Chests to a single Furnace using 3 Hoppers.",
"If you have a building devoted to the storage of a specific item, turn it into a shop. If you have a potion room, build a potion shop.",
"Construct an oasis in a nearby desert. Add some tropical trees, a hammock, a lake, and some plant life.",
"Slide down a honey block to slow your fall",
"Activate a Conduit",
"Build a path that twists precariously around a tall mountain. At the top, build a shrine to something. I recommend Cthulhu, personally.",
"The obsidian pillars in the end extend all the way to the bottom of the world, poking through the bottom of the end island. Build a large disk that is held up by these pillars and build something grand on top of it. Maybe a Spellcrafting Circle?",
"Find the highest point in your base and build a tower. Make sure the area has a good view of your base. Build an observatory room on top with glass floors and walls.",
"Travel about 100 blocks above your base and build a flying saucer. Below it build a beacon beam and have the beam travel right through the center of the ship. So it looks like it's using a tractor beam.",
"Build a large dragon hanging off of the side of a tower or another tall object.",
"Feed a dolphin fish to have it lead you to treasure",
"Remove all of the small trees and bushes from a jungle biome and build a town underneath the massive jungle trees. Bonus points: You'll actually get ocelots to spawn.",
"Find an ocean and build atlantis. Make sure there are plenty of lights so it can be seen from the surface.",
"Poison a witch with a splash potion",
"Create your own biome by terraforming your own area. You could create a volcanic wasteland using obsidian, black stained clay, lava blocks and lava formations, or create a lush green forest complete with custom trees, vines running from tree to tree, and wild carrot plants.",
"Replace the floor, ceiling or walls of a build with a large fish tank.",
"Carve an evil lair into the area below a mountain. Your evil scientist is going to need labs, a fusion reactor, a bunch of oddly specific vehicles such as a submarine with a massive claw, and at least one missile silo placed in the middle of the mountain.",
"Build a massive nether hub with portals that connect all of your various bases, farms and other locations of interest in the overworld.",
"Design and craft a bunch of custom banners and use them to tell at a glance what different rooms and areas are for. A potion icon for your potion room, a sword icon for an armory, an evil eye for your end portal, etc.",
"Place four Sea Pickles in a group",
"Build a dark and scary mob arena. Find a double or triple spawner and make a water stream that pipes all the mobs into a large dark room. Once enough of them are in the room, go in and fight them all.",
"Push a piston with a piston, then pull the original piston with that piston",
"Tame a horse",
"Spice up a desert biome with the large skeletons of great beasts. For example, this scene from Pitch Black.",
"Craft up a bunch of fireworks and hoste a fireworks display. If you happen to have crazy amounts of them, set it up so a small firework show goes off every night.",
"Create a large map wall with an overview of your base. Put it somewhere with a lot of visibility so you can always see your awesome builds.",
"Dry a sponge in a furnace",
"Power a Furnace with Lava",
"Collect dragons breath in a glass bottle",
"Teleport over 100 meters from a single throw of an Ender Pearl",
"Respawn the Enderdragon",
"Craft up about ten stacks of signs and place them all over your world in obscure places. Write something like "[player] was here" on them. Place them in caves, on the ocean floor, behind walls, on the tops of trees, and on the tops of hills. Every once in a while you'll be exploring a jungle and you'll find a sign. I'm sure it will amuse you every time.",
"Use Riptide to give yourself a boost",
"Bored of bridges? Dug tunnels underneath rivers and other obstacles. It's more impressive because it's totally impractical.",
"Build a friendly whale just floating in an ocean. Fish, giant squids and submarines also good options.",
"Breed a mule from a horse and a donkey",
"Stay underwater for 2 minutes",
"Cook and Eat Rabbit Meat",
"Defeat an Elder Guardian",
"Create a MASSIVE Nether Portal with Tentacles coming out crawling around the room",
"Make a giant quarry with Chest Minecarts travelling between the bottom and top. Add some sand heaps on the outside and maybe a crane.",
"Build compact yet detailed statues around your fortress base Build an epic fight between a sea creature and some ships in the deep ocean",
"Build compact yet detailed statues around your fortress base",
"Build an epic fight between a sea creature and some ships in the deep ocean",
"Power a furnace with a kelp block",
"Construct an enormous chest room",
"Build a race track for horses, boats, or pigs",
"Build a sky base. I recommend having fun with geometry and symmetry when building these.",
"Create a building specifically for your end portal. Make it massive and extravagant.",
"Build a grand library complete with massive, story-high book shelves, a librarian, and a few areas dedicated to lying down and reading a book.",
"Create lore for your world (make relics an cities to play a story and a part in the lore. Roleplay a bit in your head. Its your world you can do anything you want to it)",
"Build a horse stable",
"Build bridges over pesky waterways. This will make traversing your world as painless as possible.",
"Remove all torches in your base and try use clever and better-looking lighting.",
"Dig up a buried treasure",
"Spend a day underwater",
"Make a Svalbard seed bank then find all the saplings and food plants and put them all in the seed bank in case of disaster!",
"Find a naturally generating structure such as a desert pyramid or a village and make it your own.",
"Find an aesthetic block you've never tried to use before and put it to use. Red sandstone, red nether brick, acacia wood, all flavors of stained clay and coal blocks all look great but don't see much use. If you haven't tried to build with one, try it out!",
"Levitate up 50 blocks from the attacks of a Shulker",
"Use Elytra to fly through a 1 by 1 gap while moving faster than 40 m/s",
"Build something from real life in game. This can be anything from a mcDonolds to The houses of parliament",
"Expand a desert pyramid. Include a massive network of underground tunnels, tombs and a labyrinth. Replace the drop shaft and TNT trap with a large treasure room and a much more impressive array of traps.",
"Collect a fish in a bucket",
"Convert a nether fortress into a futuristic paradise. Convert the bridges into suspended roads with gardens hanging below them. Add houses, stores, libraries, parks and other buildings onto these roads. Add several large glass biodomes, giving a hint of life to the nether.",
"Upgrade a village into a military compound complete with jets, anti-air cannons, boats if it's close to water, an armory and a plaque to honor fallen testificates. They're not villagers any more, they're soldiers.",
"Acquire a map from a cartographer villager, then enter the revealed structure",
"Name a Shulker Box with an Anvil",
"Use the Totem of Undying to cheat death",
"Expand an ocean monument into a sprawling underwater city defended by the great and powerful elder guardian.",
"Renovate a jungle temple into a gold and trap filled monument Indiana Jones would be proud to raid.",
"Find a shipwreck",
"Turn a witch hut into the candy house from Hansel and Grettle.",
"Convert a woodland mansion into an evil mage's paradise. You'll need a spellbinding circle, an apothecary, a bunch of skulls and other dark imagery, some sort of altar or shrine and a place to sacrifice sheep. Oh, and a library.",
"Turn a desert well into a detailed fountain",
"Convert an end city into a wizard tower. It's already purple and tower shaped.",
"Create a sustainable living environment underground. You should be able to survive there without reaching the surface for all eternity if you so choose. Bonus points if you build fallout shelters.",
"Create a large floating island ripe with vegetation. When it's done, sit on your new island and watch the sunset.",
"Convert a ravine from boring stone into a lush garden.",
"Combine minecarts, detector rails and lamps to create a light show",
"Create a large temple inside a mountain reaching from bedrock to cloud height",
"Defeat an Evoker",
"Build your best impression of your annoying neighbors house, and bomb it with your best tnt cannon.",
"Choose a peak that overlooks some nice scenery and build a wizard tower.",
"Build a zoo, preferably in the end. Try to bring a few of every type of mob in the game, and build habitats for all of them.",
"Build a library with written books containing everything you need to remember about your world. Important coordinates, how to operate your various redstone devices, tips and tricks, the password for that redstone door you swear you'll always remember the password to, etc. Some day you'll thank yourself.",
"Build a horse testing track that looks like the kind you'd expect to find in real life. Include bars the horse must jump over to test the horse's jump height, and a redstone horse speedometer disguised as a race track. Use these to figure out which horses are good breed stock.",
"Visit all ocean biomes",
"Eat nothing but dried kelp for three in-game days",
"Using the Frost Walker boots, walk on at least 1 block on frozen water on a deep ocean",
"Lead a Caravan containing at least 5 Llamas",
"Build a large forge under your iron farm. Make it look like iron golems are being smelted into molten metal (use lava), cast into ingot shapes and distributed into chests. Bonus points for assembly lines, foundries, ventilation systems and other pieces of infrastructure to sell the appeal.",
"Build a mob farm shaped like a giant sword",
"ind a village and jump down the well. Create a secret base down there. The well must be the only way in or out. I recommend ender pearls or a slime block launcher to get back out.",
"Move a nether fortress to the overworld.",
"Build an underground base inside of a cave.",
"Find an underwater ruin",
"Collect a full stack of Wood.",
"Make a full set of Wooden Tools.",
"Build a simple house.",
"Collect two full stacks of cobblestone.",
"Make a full set of Stone Tools.",
"Make a simple defensive structure for your house. (Fences, Snowmen, Secondary set of walls.)",
"Collect 16 Wheat Seeds.",
"Build a simple farm near a water source.",
"Make upgrades to your house. (Second floor, Material changes, Expansions.)",
"Explore a cave. (Remember to bring extra sets of tools.)",
"Collect a full stack of coal or Make a full stack of charcoal.",
"Collect 20 Iron.",
"create a mountain outpost",
"find/explore an abandoned mineshaft",
"create a mob grinder",
"Bake a cake using: wheat, sugar, milk and eggs.",
"Catch and cook a fish",
"Construct an Enchantment Table",
"Use a saddle to ride a pig, and then have the pig get hurt from fall damage while riding it.",
"create a nether portal and explore the nether",
"make or expand a wheat farm",
"Destroy a Ghast with a fireball",
];